### ISSUE TITLE
Add support for critical.css

### ISSUE THREAD

**Issue by thymikee** [xfiveco/generator-chisel#67] opened 2016-10-12 10:59 UTC

**Comment by danekszy** [comment] 2016-10-14 14:20
@thymikee Is this about automation?
I suggested such approach, but it is based on headless browser running critical style scanning script... This may not always work as intended (due to bugs), which is what we discovered in #31 (visual regression testing).
Other than this caveat, I'm all in. 👍

**Comment by thymikee** [comment] 2016-10-14 14:24
This is something I've setup once for one Chisel project and I wanted to port it to general purposes.
The task is going to be fired during build.
https://github.com/addyosmani/critical

**Comment by danekszy** [comment] 2016-10-14 14:28
+1 for that, since it'll probably be optional anyway. But my point above is sth that we need to have in mind and/or add to the docs.
Ping me if you'll need any help with it (eg. testing etc.). 😉

**Comment by luboskmetko** [comment] 2016-10-14 14:40
Nice to see this but can we maybe move it to 0.5 milestone as there is a lot going on in 0.4 already In 0.5 there is mostly CSS related stuff now.

**Comment by thymikee** [comment] 2016-10-14 14:41
Regarding being optional – time to first paint is pretty crucial these days, especially for mobile  devices. I'd rather like to have it switched on by default, even if a dev is not familiar with the approach (we surely need to document it)

**Comment by danekszy** [comment] 2016-10-14 14:50
Yeah, I definitely know that #perfmatters 😉 ...
But this isn't that straightforward and may cause some bugs.
I believe our defaults should reflect most use cases/developer preferences and have lowest possible barrier of entry/learning curve. We should absolutely recommend such features in docs and educate our devs, but I wouldn't nag anybody.
Also from my experience, clients rarely want this kind of "architecture", because it isn't that simple to implement on their side.

Ultimately this should be a decision made by @arturkot, @luboskmetko or anyone else that keeps in touch with many of our developers daily.

**Comment by thymikee** [comment] 2016-10-14 14:52
So we can make it optional, but make it checked by default 😄

**Comment by luboskmetko** [comment] 2016-10-17 06:32
Let's see how reliably such automatic task works and then we could decide if we check it by default. Also we need to document how to switch this off during development so even a regular developer can do if they run into a trouble.

Would be interesting to see this implemented on WP projects too but there often can happen that plugins use their own render blocking styles and scripts.

**Comment by luboskmetko** [comment] 2017-08-21 12:31
Looks like soon it will be a good time to start working on implementation of this - critical should migrate to headless Chrome once it's implemented in Penthouse - https://github.com/addyosmani/critical/issues/229

**Comment by luboskmetko** [comment] 2017-09-20 11:46
Penthouse is now 1.0 using Chrome headless https://medium.com/@pocketjoso/penthouse-1-0-official-release-ece995b0d29e

**Comment by luboskmetko** [comment] 2018-02-22 15:31
@arturkot @jakub300 @marcinkrzeminski I'm thinking about closing this one as `wontfix`. Over the time I've started to agree that this it not much benefit on regular projects as it provides minimal performance improvement. 

We can still show implementation in a recipe at some point, but this option doesn't have to be part of Chisel (especially with the current focus on WP and simplification of the generator usage).

Let me know what you think. Thanks

**Comment by arturkot** [comment] 2018-02-23 08:09
@lubos I think we can close this one. 👍

**Closed** 2018-02-23 15:05 UTC
Labels: wontfix
